#cloud-config
autoinstall:
  version: 1
  locale: de_DE.UTF-8
  timezone: Europe/Berlin
  keyboard:
    layout: de
  late-commands:
    - curtin in-target -- chown -R filip:filip /home/filip/
    - curtin in-target -- mkdir -p /home/filip/.config
    - curtin in-target -- touch /home/filip/.config/gnome-initial-setup-done
    - curtin in-target -- chown -R filip:filip /home/filip/.config
    - curtin in-target -- mkdir -p /etc/skel/.config
    - curtin in-target -- touch /etc/skel/.config/gnome-initial-setup-done
    - curtin in-target -- systemctl mask gnome-initial-setup.service
  identity:
    hostname: filip-pc
    username: filip
    password: "$6$1/dSyfYRt5GcmZJb$mpv31f/efXP8gY939b90WM0TlLXeSuok3BgztfA0aLcvaH2SJBBTlHJIpDejK6ETw5PqftVjQZji1n6riu9KX0"
